### PR TITLE
Merge Bitcoin-ABC v0.24.11 into Lotusd

### PR DESCRIPTION
**Pull request by PiRK**
This merges Bitcoin-ABC into lotusd 

There are still failing tests. I'm opening this pull request so it is easier to see what is going on (which commits are included in this merge), and have more eyes look at the error messages.

### CODE REVIEW

**Comment by PiRK** [comment]
I'm down to 3 functional test failures:
```
interface_nng.py                          | ✖ Failed  | 2 s
logos_feature_new_block_header.py         | ✖ Failed  | 13 s
p2p_blocksonly.py                         | ✖ Failed  | 61 s
```

The nng failure is just a deprecation warning with python 3.10 interpreted as a failure by the test framework (non-empty stderr).

The other 2 are caused by peers disconnecting when we send blocks. T'm still not sure what causes this.

```
p2p_blocksonly.py failed, Duration: 61 s

stdout:
2022-10-12T07:37:45.666000Z TestFramework (INFO): Initializing test directory /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/p2p_blocksonly_8
2022-10-12T07:37:46.062000Z TestFramework (INFO): Tests with node running in -blocksonly mode
2022-10-12T07:37:46.163000Z TestFramework (INFO): Check that txs from P2P are rejected and result in disconnect
2022-10-12T07:37:46.286000Z TestFramework (INFO): Check that txs from rpc are not rejected and relayed to other peers
2022-10-12T07:38:46.428000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
        def test_function():
            if check_connected:
                assert self.is_connected
            return test_function_in()
'''
2022-10-12T07:38:46.428000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/pierre/dev/lotusd/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/home/pierre/dev/lotusd/test/functional/p2p_blocksonly.py", line 26, in run_test
    self.blocksonly_mode_tests()
  File "/home/pierre/dev/lotusd/test/functional/p2p_blocksonly.py", line 45, in blocksonly_mode_tests
    tx_relay_peer.wait_for_tx(txid)
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 537, in wait_for_tx
    self.wait_until(test_function, timeout=timeout)
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 517, in wait_until
    wait_until_helper(test_function, timeout=timeout, lock=p2p_lock,
  File "/home/pierre/dev/lotusd/test/functional/test_framework/util.py", line 287, in wait_until_helper
    raise AssertionError(
AssertionError: Predicate ''''
        def test_function():
            if check_connected:
                assert self.is_connected
            return test_function_in()
''' not true after 60.0 seconds
2022-10-12T07:38:46.479000Z TestFramework (INFO): Stopping nodes
2022-10-12T07:38:46.630000Z TestFramework (WARNING): Not cleaning up dir /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/p2p_blocksonly_8
2022-10-12T07:38:46.630000Z TestFramework (ERROR): Test failed. Test logging available at /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/p2p_blocksonly_8/test_framework.log
2022-10-12T07:38:46.630000Z TestFramework (ERROR):
2022-10-12T07:38:46.630000Z TestFramework (ERROR): Hint: Call /home/pierre/dev/lotusd/test/functional/combine_logs.py '/home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/p2p_blocksonly_8' to consolidate all logs
2022-10-12T07:38:46.630000Z TestFramework (ERROR):
2022-10-12T07:38:46.630000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-10-12T07:38:46.630000Z TestFramework (ERROR): https://github.com/LogosFoundation/lotusd/issues
2022-10-12T07:38:46.631000Z TestFramework (ERROR):

stderr:
```


```
logos_feature_new_block_header.py failed, Duration: 13 s

stdout:
2022-10-12T07:39:53.015000Z TestFramework (INFO): Initializing test directory /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/logos_feature_new_block_header_196
2022-10-12T07:40:05.657000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/pierre/dev/lotusd/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/home/pierre/dev/lotusd/test/functional/logos_feature_new_block_header.py", line 257, in run_test
    peer.send_blocks_and_test([block], node)
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 819, in send_blocks_and_test
    test()
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 798, in test
    self.wait_until(
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 517, in wait_until
    wait_until_helper(test_function, timeout=timeout, lock=p2p_lock,
  File "/home/pierre/dev/lotusd/test/functional/test_framework/util.py", line 272, in wait_until_helper
    if predicate():
  File "/home/pierre/dev/lotusd/test/functional/test_framework/p2p.py", line 514, in test_function
    assert self.is_connected
AssertionError
2022-10-12T07:40:05.708000Z TestFramework (INFO): Stopping nodes
2022-10-12T07:40:05.859000Z TestFramework (WARNING): Not cleaning up dir /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/logos_feature_new_block_header_196
2022-10-12T07:40:05.859000Z TestFramework (ERROR): Test failed. Test logging available at /home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/logos_feature_new_block_header_196/test_framework.log
2022-10-12T07:40:05.859000Z TestFramework (ERROR):
2022-10-12T07:40:05.859000Z TestFramework (ERROR): Hint: Call /home/pierre/dev/lotusd/test/functional/combine_logs.py '/home/pierre/dev/lotusd/build/test/tmp/test_runner_₿₵_🏃_20221012_093744/logos_feature_new_block_header_196' to consolidate all logs
2022-10-12T07:40:05.859000Z TestFramework (ERROR):
2022-10-12T07:40:05.859000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-10-12T07:40:05.859000Z TestFramework (ERROR): https://github.com/LogosFoundation/lotusd/issues
2022-10-12T07:40:05.859000Z TestFramework (ERROR):

stderr:

```

**Comment by PiRK** [comment]
The p2p_blocksonly failure was just a txhash that need to be replaced by a txid.

**Comment by PiRK** [comment]
I fixed an intermittent failure in interface_zmq.py. Occasionnaly the UTXO used for creating the conflicting transaction would not be sufficient to work with the hardcoded amount and change. I changed the code so that these amounts are no longer hardcoded but rather depend on the used utxo.


```
diff --git a/test/functional/interface_zmq.py b/test/functional/interface_zmq.py
index bae9836b7..91ab24622 100755
--- a/test/functional/interface_zmq.py
+++ b/test/functional/interface_zmq.py
@@ -308,11 +308,13 @@ class ZMQTest (BitcoinTestFramework):
             called. Return the TxId."""
             address = self.nodes[1].getnewaddress()
             change_address = self.nodes[1].getrawchangeaddress()
+            amount = (utxo["amount"] / 2).quantize(Decimal('.000001'))
+            change_amount = utxo["amount"] - (amount + Decimal("0.1"))
             tx = self.nodes[1].signrawtransactionwithwallet(
                 self.nodes[1].createrawtransaction(
                     inputs=[{"txid": utxo["txid"], "vout": utxo["vout"]}],
-                    outputs=[{address: 5},
-                             {change_address: utxo["amount"] - Decimal("5.1")}]
+                    outputs=[{address: amount},
+                             {change_address: change_amount}]
                 )
             )
             return send_node.sendrawtransaction(tx["hex"])

```

**Comment by schancel** [comment]
Thanks pirk. Going to disable the failing test and merge this into master.

**Comment by schancel** [comment]
Manually merged. Closing outside normal github flow

**Pull request closed without merging**
