### PR TITLE
Add activation code for Judges upgrade

### PR DESCRIPTION
**Pull request by maff1989**
Make all necessary preparations for the Judges upgrade June 20 2024. Used previous Joshua upgrade commits as template for this commit.

~Still need to add the Python test.~ [f6ba1a7](https://github.com/givelotus/lotusd/pull/314/commits/f6ba1a7686428970bcdb9ec53e844e21d1adafe0)

### CODE REVIEW

**Comment by maff1989** [comment]
@schancel I removed you from the reviewers to try and just push through the merge myself. But I'll wait for you to handle it.

**Comment by maff1989** [comment]
image

**Comment by maff1989** [comment]
@schancel please review, I'm not sure if I screwed up the python test or if that's expected to fail at this point.

**Comment by maff1989** [comment]
@schancel bump

**Comment by schancel** [comment]
Joy. Teamcity is not working. I will have to investigate later.

**Pull request merged**
